use_frameworks!
platform :ios, '10.0'

source 'https://github.com/ResearchSuite/Specs.git'
source 'https://github.com/CuriosityHealth/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'LS2SDK_Example' do
  pod 'LS2SDK', :git => 'https://github.com/CuriosityHealth/LS2SDK-iOS'
  pod 'OMHClient'
  pod 'ResearchSuiteExtensions', :git => 'https://github.com/ResearchSuite/ResearchSuiteExtensions-iOS'
  pod 'ResearchSuiteResultsProcessor', :git => 'https://github.com/ResearchSuite/ResearchSuiteResultsProcessor-ios'

  target 'LS2SDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
